import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Particles from 'react-tsparticles';
import { useRouter } from 'next/router';
import { loadStarsPreset } from 'tsparticles-preset-stars';
import { loadFull } from 'tsparticles';
import { AiFillGithub } from 'react-icons/ai';
import { SubmitHandler, useForm } from 'react-hook-form';
import axios from 'axios';
import { GetServerSidePropsContext } from 'next';
import styles from '../styles/Auth.module.scss';
import AuthBox from '../components/AuthBox';
import Checkbox from '../components/Checkbox';
import { Google } from '../public';
import { fetchUser, userApiUrl } from '../components/utils';

type FormValues = { email: string; password: string };

const Login = (): JSX.Element => {
    const { register, handleSubmit } = useForm<FormValues>();
    const router = useRouter();

    const login: SubmitHandler<FormValues> = data => {
        axios
            .post(
                `${userApiUrl}/session`,
                {
                    ...data,
                },
                {
                    headers: {
                        Accept: 'application/json',
                        'Content-Type': 'application/json',
                    },
                    withCredentials: true,
                },
            )
            .then(async res => {
                if (res.status === 200) {
                    await router.push('/dashboard');
                }
            })
            .catch(err => console.error(err));
    };

    return (
        <>
            <Head>
                <title>Galactic Nodes</title>
                <meta name={'description'} content={'Generated by create next app'} />
                <link rel={'icon'} href={'/favicon.ico'} />
            </Head>
            <main className={styles.main}>
                <div className={styles.mainSector}>
                    <Particles
                        style={{
                            position: 'absolute',
                            top: 0,
                            zIndex: 5,
                        }}
                        height={'100%'}
                        width={'100%'}
                        options={{
                            preset: 'stars',
                            background: { color: 'transparent' },
                            particles: {
                                number: {
                                    value: 350,
                                },
                                move: {
                                    speed: 0.4,
                                },
                            },
                            fullScreen: false,
                        }}
                        init={async engine => {
                            await loadStarsPreset(engine);
                            await loadFull(engine);
                        }}
                    />
                    <form onSubmit={handleSubmit(login)}>
                        <AuthBox>
                            <div>
                                <label htmlFor={'email'}>
                                    <p>Email</p>
                                    <input id={'email'} {...register('email', { required: true })} type={'text'} />
                                </label>
                            </div>
                            <div>
                                <label htmlFor={'password'}>
                                    <p>Password</p>
                                    <input id={'password'} {...register('password', { required: true })} type={'password'} />
                                </label>
                            </div>
                            <div className={styles.remember}>
                                <Checkbox label={'Remember Me'} />
                            </div>
                            <button type={'submit'} className={styles.gnButton}>
                                Login
                            </button>
                            <h6 className={styles.accountQuestion}>
                                Don&apos;t have an account? <a href={'/signup'}>Sign Up</a>
                            </h6>
                            <a href={'/login/google'} className={styles.googleLogin}>
                                <Image src={Google} />
                                <p>Sign in with Google</p>
                            </a>
                            <a href={'/login/github'} className={styles.githubLogin}>
                                <AiFillGithub />
                                <p>Sign in with Github</p>
                            </a>
                        </AuthBox>
                    </form>
                    <div className={styles.loginBox} />
                </div>
            </main>
        </>
    );
};

export const getServerSideProps = async ({ req }: GetServerSidePropsContext) => {
    const user = await fetchUser(req.headers.cookie || '');
    if (user.data) {
        return {
            redirect: {
                destination: '/dashboard',
                permanent: false,
            },
        };
    }
    return {
        props: {},
    };
};

export default Login;
